// Placeholder firebase options. Replace with values generated by `flutterfire configure`.
// This file is provided to keep the project compiling until real Firebase config is added.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return android;
    }
  }

  // TODO: Replace dummy values with real config from Firebase console via `flutterfire configure`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'DUMMY',
    appId: 'DUMMY',
    messagingSenderId: 'DUMMY',
    projectId: 'DUMMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'DUMMY',
    appId: 'DUMMY',
    messagingSenderId: 'DUMMY',
    projectId: 'DUMMY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'DUMMY',
    appId: 'DUMMY',
    messagingSenderId: 'DUMMY',
    projectId: 'DUMMY',
    iosBundleId: 'com.example.examace',
  );

  static const FirebaseOptions macos = ios;
  static const FirebaseOptions windows = android;
  static const FirebaseOptions linux = android;
}
